#Orange WZ \u2014 UTF-8
#Wed May 06 09:38:58 CST 2026
exportXml.exportPath=E\:\\0SKIll\\server
exportXml.indent=0
exportXml.lineSeparator=windows
exportXml.media=NONE
exportXml.version=V125
preview.cacheEnabled=false
preview.includeEnglishNamed=true
preview.includeIconNamed=false
preview.includeNumericNamed=false
