#Orange WZ \u2014 UTF-8
#Thu May 07 11:11:30 CST 2026
exportXml.exportPath=E\:\\0SKIll\\server
exportXml.indent=0
exportXml.lineSeparator=windows
exportXml.media=NONE
exportXml.version=V125
preview.cacheEnabled=false
preview.includeEnglishNamed=false
preview.includeIconNamed=true
preview.includeNumericNamed=false
