#Orange WZ \u2014 UTF-8
#Sat Jul 04 11:34:41 CST 2026
exportJson.exportPath=G\:\\273\\XMLOUT
exportJson.indent=2
exportXml.exportPath=E\:\\0SKIll\\server
exportXml.indent=0
exportXml.lineSeparator=windows
exportXml.media=NONE
exportXml.version=V125
preview.cacheEnabled=false
preview.includeEnglishNamed=true
preview.includeIconNamed=false
preview.includeNumericNamed=false
